---
apiVersion: v1
kind: Secret
metadata:
  name: kcdnyc-demo-wheres-teddy-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/kcdnyc-demo-wheres-teddy-gitops
